name: Test Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry/cache
            ~/.foundry/artifacts
            out
            cache
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}-${{ hashFiles('**/remappings.txt') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Run Forge coverage
        run: forge coverage --report lcov --ir-minimum
        env:
          FOUNDRY_PROFILE: ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: foundry
          name: foundry-coverage
          fail_ci_if_error: false